In [2]:
import pandas as pd
import json
import numpy as np
from tqdm import tqdm
from os import listdir
from collections import Counter
from keras.utils import to_categorical

Using TensorFlow backend.

In [ ]:
indir = "/home/doodle/pedro/data/training_data_grouped/"

In [ ]:
outdir =  "/home/doodle/pedro/data/training_data_grouped_trimmed/"

In [ ]:
files = list(listdir(indir))

In [ ]:
counts = Counter()

In [ ]:
for file in tqdm(files):
    name = file.split(".")[0]
    counts[name] += len(pd.read_csv(indir+file))

In [ ]:
json.dump(counts, open("/home/doodle/pedro/data/counts.json", "w"))

In [ ]:
total = sum(counts.values())

In [ ]:
samples = {} 
for name, count in counts.items():
    samples[name] = int(count*100000/total)

In [ ]:
validation = []

In [ ]:
for file in tqdm(files):
    name = file.split(".")[0]
    df = pd.read_csv(indir+file)
    train, validate = np.split(df.sample(frac=1), [len(df)-samples[file.split('.')[0]]])
    validation.append(validate)
    train.to_csv(outdir+file, index=False)

In [ ]:
validation_df = pd.concat(validation)

In [ ]:
validation_df.to_csv("/home/doodle/pedro/data/validation.csv", index=False)

In [9]:
validation_df = pd.read_csv("/home/doodle/pedro/data/validation.csv")

In [11]:
validation_df

,countrycode,drawing,key_id,recognized,timestamp,word
0,GB,"[[[136, 102, 51, 28, 10, 3, 0, 5, 55, 88, 180,...",6105569792360448,True,2017-01-31 14:02:08.044260,pond
1,FI,"[[[34, 30, 36, 69, 80, 93, 105, 117, 141, 205,...",5859652694704128,True,2017-03-19 10:37:38.259160,pond
2,US,"[[[53, 52, 71, 104, 163, 198, 213, 233, 246, 2...",6101342135255040,True,2017-01-27 18:37:58.789090,pond
3,UA,"[[[72, 50, 12, 2, 0, 0, 10, 25, 41, 66, 90, 11...",4862391839883264,True,2017-03-06 18:12:50.084800,pond
4,ME,"[[[167, 159, 132, 54, 38, 15, 0, 2, 15, 40, 53...",5025288289255424,True,2017-03-29 19:14:24.450560,pond
5,US,"[[[182, 128, 113, 94, 71, 41, 11, 0, 1, 9, 63,...",4626044524953600,True,2017-01-23 14:48:56.476970,pond
6,IT,"[[[155, 105, 81, 52, 40, 25, 3, 0, 9, 33, 39, ...",6079978359750656,True,2017-03-08 09:13:40.588940,pond
7,US,"[[[225, 215, 166, 143, 119, 106, 83, 72, 34, 7...",5783115794481152,True,2017-01-26 17:02:25.996990,pond
8,US,"[[[114, 88, 67, 47, 30, 20, 12, 4, 0, 1, 11, 3...",6475468763037696,True,2017-03-28 03:00:47.834010,pond
9,BE,"[[[132, 128], [33, 39]], [[100, 88, 39, 25, 10...",4647804385361920,True,2017-03-16 06:25:07.426870,pond
10,US,"[[[168, 126, 61, 31, 14, 2, 0, 4, 17, 36, 108,...",6343695794176000,True,2017-03-09 19:02:02.658770,pond
11,CA,"[[[58, 40, 19, 16, 22, 38, 52, 73, 110, 163, 2...",6535609160040448,False,2017-03-09 19:50:57.480510,pond
12,US,"[[[188, 177, 137, 65, 15, 9, 1, 0, 4, 18, 32, ...",6739316841644032,True,2017-03-08 02:20:23.062610,pond
13,US,"[[[45, 63, 113, 151, 234, 247, 253, 255, 234, ...",5787430772801536,True,2017-03-24 17:10:17.917150,pond
14,AU,"[[[216, 169, 104, 74, 29, 15, 4, 0, 2, 19, 33,...",5268128021872640,True,2017-03-23 09:45:13.271650,pond
15,PK,"[[[77, 48, 33, 22, 22, 33, 5, 0, 5, 25, 44, 59...",4835058013700096,True,2017-03-27 11:35:34.888590,pond
16,BR,"[[[105, 32, 19, 8, 1, 1, 9, 26, 73, 127, 199, ...",5773606262931456,True,2017-03-14 21:57:39.019760,pond
17,US,"[[[255, 232, 160, 57, 21, 10, 2, 0, 3, 15, 44,...",4912005137825792,True,2017-03-16 18:01:23.659760,pond
18,FI,"[[[217, 168, 126, 76, 41, 6, 1, 0, 3, 28, 56, ...",6612137977839616,True,2017-03-26 21:44:19.536650,pond
19,CA,"[[[116, 74, 44, 17, 6, 0, 5, 30, 41, 43, 48, 5...",5235883810750464,True,2017-01-28 03:41:54.698830,pond
20,ID,"[[[0, 31, 79, 94, 122, 154, 177, 215, 228, 243...",5114867734282240,True,2017-03-06 10:27:33.067480,pond
21,NL,"[[[90, 77, 71, 48, 11], [17, 23, 31, 49, 50]],...",5915751443595264,True,2017-03-27 09:12:19.494980,pond
22,US,"[[[122, 97, 54, 17, 5, 0, 7, 32, 50, 153, 236,...",5551203259777024,True,2017-03-08 20:24:51.235330,pond
23,US,"[[[172, 110, 73, 59, 35, 19, 9, 1, 1, 18, 150,...",5823585203519488,True,2017-03-26 14:12:55.430600,pond
24,US,"[[[239, 216, 175, 153, 97, 46, 16, 2, 1, 12, 2...",6193511676248064,True,2017-03-29 11:32:10.891990,pond
25,RO,"[[[60, 97, 143, 162, 165, 164, 154, 144, 130, ...",4571824031531008,True,2017-03-25 18:44:49.007610,pond
26,US,"[[[194, 187, 170, 133, 117, 112, 113, 102, 86,...",6061485824409600,True,2017-03-20 00:29:34.062240,pond
27,US,"[[[232, 207, 181, 134, 103, 76, 43, 19, 7, 0, ...",5574268022685696,True,2017-03-16 21:16:36.769160,pond
28,US,"[[[168, 132, 83, 46, 13, 5, 0, 0, 13, 38, 58, ...",6269542177177600,True,2017-03-06 19:20:35.284130,pond
29,US,"[[[52, 88, 135, 179, 229, 253, 251, 241, 239, ...",5675684032675840,True,2017-01-26 17:13:57.601060,pond
...,...,...,...,...,...,...
99807,US,"[[[70, 55, 31, 29, 38, 60, 98], [234, 230, 234...",5367433189654528,True,2017-01-22 04:16:44.306830,kangaroo
99808,RU,"[[[62, 28, 16, 5, 1], [248, 255, 254, 247, 233...",5513015279484928,True,2017-03-19 12:21:32.795700,kangaroo
99809,IT,"[[[64, 64], [255, 255]], [[71, 3, 1, 1, 7, 23,...",6596660857667584,True,2017-01-09 15:04:39.356600,kangaroo
99810,US,"[[[131, 131, 143, 158, 188, 202, 204, 201, 172...",5235947060854784,True,2017-01-24 20:26:44.350090,kangaroo
99811,US,"[[[80, 82, 80, 64, 41, 15, 0, 16, 59, 176, 185...",5884268980994048,True,2017-03-03 13:13:02.107410,kangaroo
99812,PH,"[[[46, 42, 43, 53, 56, 60, 65, 123, 129, 129, ...",5900666805420032,True,2017-04-04 05:01:10.196800,kangaroo
99813,CZ,"[[[101, 97, 82, 61], [185, 215, 219, 218]], [[...",6255982139146240,True,2017-01-04 01:38:20.657850,kangaroo
99814,BR,"[[[167, 169, 175, 191, 199, 211, 213, 220, 235...",6274750500306944,True,2017-01-26 02:15:20.328150,kangaroo
99815,US,"[[[52, 53, 62, 79, 92, 80, 73, 68], [32, 24, 1...",6548994425618432,True,2017-03-14 15:15:10.425090,kangaroo
99816,ZA,"[[[255, 227, 199, 175, 158, 151, 158, 130, 112...",4541689349799936,True,2017-03-03 11:14:36.639240,kangaroo
99817,AU,"[[[145, 145, 149, 155, 164, 172, 172], [25, 11...",5627426094710784,True,2017-03-21 06:12:44.700180,kangaroo
99818,RU,"[[[17, 33, 42, 51, 59, 66, 93, 128], [41, 44, ...",5149324449153024,True,2017-01-31 14:30:49.767800,kangaroo
99819,GB,"[[[86, 88, 100, 111, 119, 120, 109, 118, 120, ...",4977645710213120,True,2017-03-02 12:11:43.091890,kangaroo
99820,US,"[[[160, 183, 218, 220, 214, 155, 125], [180, 1...",6374935343661056,True,2017-01-23 17:24:29.146690,kangaroo
99821,ID,"[[[65, 46, 19, 5, 0, 1, 25, 41], [41, 36, 36, ...",5934630169477120,True,2017-01-07 02:08:51.011480,kangaroo
99822,HU,"[[[143, 47, 42, 40, 37, 39, 50, 72, 117, 129, ...",5486734743699456,False,2017-03-26 18:00:10.068660,kangaroo
99823,KZ,"[[[113, 118, 130, 146, 158, 170, 214, 223, 226...",5487785387491328,True,2017-01-29 09:56:48.829000,kangaroo
99824,US,"[[[56, 53, 63, 73, 76, 80, 85, 88, 96, 98, 124...",6108777977741312,True,2017-03-19 15:41:59.490710,kangaroo
99825,TH,"[[[35, 6, 0, 8, 40, 49, 54, 59, 49, 48, 56, 66...",4937495701618688,True,2017-03-21 07:03:01.954090,kangaroo
99826,JP,"[[[139, 146, 153, 154, 149, 159, 171, 170, 161...",6578175586861056,True,2017-01-12 11:42:50.900390,kangaroo
99827,TH,"[[[55, 38, 36, 42, 65, 84, 88, 82, 62, 56], [8...",6161563931115520,False,2017-03-21 20:15:22.714310,kangaroo
99828,US,"[[[146, 170, 184, 193, 194, 189, 180, 152, 152...",6380012544458752,True,2017-03-22 02:05:22.099770,kangaroo
99829,US,"[[[3, 11, 67, 87, 107, 125, 143, 154, 175, 188...",6275091421724672,True,2017-01-09 23:45:41.747690,kangaroo
99830,SE,"[[[136, 154, 179, 204, 229, 240, 241, 227, 201...",6420310343548928,True,2017-03-21 15:22:44.118930,kangaroo
99831,US,"[[[87, 88, 87, 82, 28, 0, 35, 69, 70, 61, 58, ...",6064993688616960,True,2017-03-05 22:34:21.450020,kangaroo
99832,TH,"[[[114, 116, 131, 123], [71, 63, 58, 72]], [[1...",6475776843055104,True,2017-03-08 09:37:12.717900,kangaroo
99833,CA,"[[[84, 82, 83, 103, 109, 122, 125, 131, 141, 1...",5273906799706112,True,2017-03-22 00:00:26.065410,kangaroo
99834,DE,"[[[3, 53, 65, 74, 80, 84, 97, 136, 170, 179, 1...",5951304767635456,True,2017-01-31 19:17:39.575650,kangaroo
99835,HU,"[[[0, 8, 38], [45, 33, 34]], [[3, 43], [46, 43...",6081415575764992,True,2017-01-12 20:14:04.621340,kangaroo
99836,BG,"[[[8, 25, 50], [71, 64, 65]], [[5, 0, 9, 35, 4...",6524492379586560,True,2017-01-29 08:27:27.583510,kangaroo

In [10]:
validation_df.sample(frac=1).to_csv("/home/doodle/pedro/data/validation.csv", index=False)

In [3]:
np.random.seed(seed=0)

class Database:
    def __init__(self):
        indir = "/home/doodle/pedro/data/training_data_grouped/"
        sorted_files = sorted(list(listdir(indir)), key=str.lower) 
        sorted_names = [file.split('.')[0] for file in sorted_files]
        class_counts = json.load(open("/home/doodle/pedro/data/counts.json"))
        total = sum(class_counts.values())
        
        self.streams = [ClassStream(indir+file,y) for y, file in enumerate(sorted_files)] 
        self.prob_dist = [class_counts[name]/total for name in sorted_names] 
        
    def get_next_batch(self, batch_size, prob_dist=None):
        if prob_dist is not None:
            self.prob_dist = prob_dist 
        X, Y = [], [] 
        num_samples = 5
        for i in range(int(batch_size/num_samples)):
            class_stream = np.random.choice(self.streams, p=self.prob_dist)
            for j in range(num_samples):
                x, y = class_stream.get_next() 
                X.append(x)
                Y.append(y)
        return X, Y 
        

class ClassStream:
    def __init__(self, file, y, chunksize=1000):
        self.y = y 
        self.samples = [] 
        self.sample_gen = self.replenish_samples(chunksize) 
        self.file = file 
    
    def get_next(self):
        if len(self.samples) == 0:
            self.samples.extend(next(self.sample_gen))
        return self.samples.pop(), self.y
    
    def replenish_samples(self, chunksize):
        while(True):
            for chunk in pd.read_csv(self.file, chunksize=chunksize):
                yield chunk['drawing']

In [6]:
db = Database()

In [7]:
for i in tqdm(range(1000)):
    X, Y = db.get_next_batch(1000)

100%|██████████| 1000/1000 [01:41<00:00, 10.44it/s]